// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbgen

import (
	"time"

	"github.com/jackc/pgtype"
)

type ReconciliationJob struct {
	ID                       int64
	Status                   string
	SystemTransactionCsvPath string
	BankTransactionCsvPaths  pgtype.JSONB
	DiscrepancyThreshold     float64
	StartDate                time.Time
	EndDate                  time.Time
	Result                   pgtype.JSONB
	CreatedAt                time.Time
	UpdatedAt                time.Time
}
