// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbgen

import (
	"context"
)

type Querier interface {
	CountReconciliationJobs(ctx context.Context) (int64, error)
	CreateReconciliationJob(ctx context.Context, arg CreateReconciliationJobParams) (ReconciliationJob, error)
	GetReconciliationJobById(ctx context.Context, id int64) (ReconciliationJob, error)
	ListPendingReconciliationJobs(ctx context.Context) ([]ReconciliationJob, error)
	ListReconciliationJobs(ctx context.Context, arg ListReconciliationJobsParams) ([]ReconciliationJob, error)
	SaveFailedReconciliationJob(ctx context.Context, arg SaveFailedReconciliationJobParams) (ReconciliationJob, error)
	SaveSuccessReconciliationJob(ctx context.Context, arg SaveSuccessReconciliationJobParams) (ReconciliationJob, error)
}

var _ Querier = (*Queries)(nil)
