// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateReconciliationJob(ctx context.Context, arg CreateReconciliationJobParams) (ReconciliationJob, error)
	FinishReconciliationJob(ctx context.Context, arg FinishReconciliationJobParams) (ReconciliationJob, error)
	GetReconciliationJobById(ctx context.Context, id int64) (ReconciliationJob, error)
	ListReconciliationJobs(ctx context.Context) ([]ReconciliationJob, error)
	UpdateReconciliationJobStatus(ctx context.Context, arg UpdateReconciliationJobStatusParams) (ReconciliationJob, error)
}

var _ Querier = (*Queries)(nil)
