// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/reconciliaton_job/processer.go
//
// Generated by this command:
//
//	mockgen -source=./service/reconciliaton_job/processer.go -destination=test/mock/service/./reconciliaton_job/processer.go
//

// Package mock_reconciliatonjob is a generated GoMock package.
package mock_reconciliatonjob

import (
	context "context"
	reflect "reflect"

	filestorage "github.com/delly/amartha/repository/file_storage"
	dbgen "github.com/delly/amartha/repository/postgresql"
	gomock "go.uber.org/mock/gomock"
)

// MockProcesser is a mock of Processer interface.
type MockProcesser struct {
	ctrl     *gomock.Controller
	recorder *MockProcesserMockRecorder
}

// MockProcesserMockRecorder is the mock recorder for MockProcesser.
type MockProcesserMockRecorder struct {
	mock *MockProcesser
}

// NewMockProcesser creates a new mock instance.
func NewMockProcesser(ctrl *gomock.Controller) *MockProcesser {
	mock := &MockProcesser{ctrl: ctrl}
	mock.recorder = &MockProcesserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcesser) EXPECT() *MockProcesserMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockProcesser) Process(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockProcesserMockRecorder) Process(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockProcesser)(nil).Process), ctx)
}

// MockProcesserRepository is a mock of ProcesserRepository interface.
type MockProcesserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProcesserRepositoryMockRecorder
}

// MockProcesserRepositoryMockRecorder is the mock recorder for MockProcesserRepository.
type MockProcesserRepositoryMockRecorder struct {
	mock *MockProcesserRepository
}

// NewMockProcesserRepository creates a new mock instance.
func NewMockProcesserRepository(ctrl *gomock.Controller) *MockProcesserRepository {
	mock := &MockProcesserRepository{ctrl: ctrl}
	mock.recorder = &MockProcesserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcesserRepository) EXPECT() *MockProcesserRepositoryMockRecorder {
	return m.recorder
}

// FailedReconciliationJob mocks base method.
func (m *MockProcesserRepository) FailedReconciliationJob(ctx context.Context, arg dbgen.FailedReconciliationJobParams) (dbgen.ReconciliationJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailedReconciliationJob", ctx, arg)
	ret0, _ := ret[0].(dbgen.ReconciliationJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailedReconciliationJob indicates an expected call of FailedReconciliationJob.
func (mr *MockProcesserRepositoryMockRecorder) FailedReconciliationJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailedReconciliationJob", reflect.TypeOf((*MockProcesserRepository)(nil).FailedReconciliationJob), ctx, arg)
}

// FinishReconciliationJob mocks base method.
func (m *MockProcesserRepository) FinishReconciliationJob(ctx context.Context, arg dbgen.FinishReconciliationJobParams) (dbgen.ReconciliationJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishReconciliationJob", ctx, arg)
	ret0, _ := ret[0].(dbgen.ReconciliationJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishReconciliationJob indicates an expected call of FinishReconciliationJob.
func (mr *MockProcesserRepositoryMockRecorder) FinishReconciliationJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishReconciliationJob", reflect.TypeOf((*MockProcesserRepository)(nil).FinishReconciliationJob), ctx, arg)
}

// ListPendingReconciliationJobs mocks base method.
func (m *MockProcesserRepository) ListPendingReconciliationJobs(ctx context.Context) ([]dbgen.ReconciliationJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingReconciliationJobs", ctx)
	ret0, _ := ret[0].([]dbgen.ReconciliationJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingReconciliationJobs indicates an expected call of ListPendingReconciliationJobs.
func (mr *MockProcesserRepositoryMockRecorder) ListPendingReconciliationJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingReconciliationJobs", reflect.TypeOf((*MockProcesserRepository)(nil).ListPendingReconciliationJobs), ctx)
}

// UpdateReconciliationJobStatus mocks base method.
func (m *MockProcesserRepository) UpdateReconciliationJobStatus(ctx context.Context, arg dbgen.UpdateReconciliationJobStatusParams) (dbgen.ReconciliationJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReconciliationJobStatus", ctx, arg)
	ret0, _ := ret[0].(dbgen.ReconciliationJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReconciliationJobStatus indicates an expected call of UpdateReconciliationJobStatus.
func (mr *MockProcesserRepositoryMockRecorder) UpdateReconciliationJobStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReconciliationJobStatus", reflect.TypeOf((*MockProcesserRepository)(nil).UpdateReconciliationJobStatus), ctx, arg)
}

// MockStorageGetter is a mock of StorageGetter interface.
type MockStorageGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStorageGetterMockRecorder
}

// MockStorageGetterMockRecorder is the mock recorder for MockStorageGetter.
type MockStorageGetterMockRecorder struct {
	mock *MockStorageGetter
}

// NewMockStorageGetter creates a new mock instance.
func NewMockStorageGetter(ctrl *gomock.Controller) *MockStorageGetter {
	mock := &MockStorageGetter{ctrl: ctrl}
	mock.recorder = &MockStorageGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageGetter) EXPECT() *MockStorageGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorageGetter) Get(ctx context.Context, filePath string) (*filestorage.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filePath)
	ret0, _ := ret[0].(*filestorage.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageGetterMockRecorder) Get(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageGetter)(nil).Get), ctx, filePath)
}
